openapi: 3.0.3
info:
    title: AI News Mailer
    description: A REST service to interact with an emailer that sends AI-summarised news
    version: "1.0"
servers:
    - url: http://localhost:8888/api
paths:
    /subscription:
        get:
            tags:
                - subscription
            summary: getAll subscription
            description: Get all subscriptions
            operationId: subscription#getAll
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Subscription'
                                description: A list of subscriptions
                                example:
                                    - email: Sed aut officia.
                                      name: Voluptas fugiat pariatur accusamus.
                                      since: Natus itaque ea.
                                      uid: Nam eos rerum quos sint.
                                    - email: Sed aut officia.
                                      name: Voluptas fugiat pariatur accusamus.
                                      since: Natus itaque ea.
                                      uid: Nam eos rerum quos sint.
                                    - email: Sed aut officia.
                                      name: Voluptas fugiat pariatur accusamus.
                                      since: Natus itaque ea.
                                      uid: Nam eos rerum quos sint.
                                    - email: Sed aut officia.
                                      name: Voluptas fugiat pariatur accusamus.
                                      since: Natus itaque ea.
                                      uid: Nam eos rerum quos sint.
                            example:
                                - email: Sed aut officia.
                                  name: Voluptas fugiat pariatur accusamus.
                                  since: Natus itaque ea.
                                  uid: Nam eos rerum quos sint.
                                - email: Sed aut officia.
                                  name: Voluptas fugiat pariatur accusamus.
                                  since: Natus itaque ea.
                                  uid: Nam eos rerum quos sint.
                                - email: Sed aut officia.
                                  name: Voluptas fugiat pariatur accusamus.
                                  since: Natus itaque ea.
                                  uid: Nam eos rerum quos sint.
                                - email: Sed aut officia.
                                  name: Voluptas fugiat pariatur accusamus.
                                  since: Natus itaque ea.
                                  uid: Nam eos rerum quos sint.
    /subscription/{uid}:
        delete:
            tags:
                - subscription
            summary: deleteOneByUID subscription
            description: Delete a subscription by UID
            operationId: subscription#deleteOneByUID
            parameters:
                - name: uid
                  in: path
                  description: UID of subscription
                  required: true
                  schema:
                    type: string
                    description: UID of subscription
                    example: Sint voluptatibus blanditiis et dolor.
                  example: Numquam ut iusto commodi pariatur.
            responses:
                "200":
                    description: OK response.
                "404":
                    description: 'SubscriptionNotFound: Error returned when the specified subscription does not exist'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - subscription
            summary: getOneByUID subscription
            description: Get a subscription by UID
            operationId: subscription#getOneByUID
            parameters:
                - name: uid
                  in: path
                  description: UID of subscription
                  required: true
                  schema:
                    type: string
                    description: UID of subscription
                    example: Ut doloremque saepe repellendus vitae.
                  example: Corrupti numquam nisi a alias eos et.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Subscription'
                            example:
                                email: Sapiente veniam quo est voluptates.
                                name: Beatae sit quas natus.
                                since: Dolores nulla.
                                uid: Fuga dolorem accusantium nihil architecto porro et.
                "404":
                    description: 'SubscriptionNotFound: Error returned when the specified subscription does not exist'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Error returned when the specified subscription does not exist
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Subscription:
            type: object
            properties:
                email:
                    type: string
                    description: Subscribed email
                    example: Qui sit.
                name:
                    type: string
                    description: Name of the subscriber
                    example: Nemo aperiam.
                since:
                    type: string
                    description: Datetime when the subscription was made
                    example: Nulla maxime aliquam.
                uid:
                    type: string
                    description: Unique identifier of subcription
                    example: Ut ut ut placeat.
            description: Representation of the subscription
            example:
                email: Esse iure.
                name: Sapiente optio.
                since: Ipsum ut.
                uid: Fugit qui.
            required:
                - uid
                - email
tags:
    - name: subscription
      description: The subscription service provides ways to manage news subscription
